version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - darwin
    goarch:
      - amd64
      - arm64
    no_unique_dist_dir: true

archives:
  - id: tar
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256

kos:
  - main: ./
    working_dir: .

    platforms:
      - linux/amd64
      - linux/arm64

    tags:
      - '{{ .Tag }}'
      - '{{ if not .Prerelease }}latest{{ end }}' 

    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.name: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.source: "{{.GitURL}}"

    sbom: none

    bare: true

nfpms:
  - file_name_template: '{{ .PackageName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    vendor: github.com/tamcore
    maintainer: github.com/tamcore
    formats:
      - apk
      - deb
      - rpm
    umask: 0o002
    bindir: /usr/bin
    contents:
    - src: ./ser2sock.service
      dst: /etc/systemd/system/ser2sock.service
      type: config
